# Generated by Django 4.0.5 on 2022-06-19 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='courses',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trainee2.course'),
        ),
    ]
