# Generated by Django 4.0.5 on 2022-06-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='courses',
        ),
    ]
